# SevenToDie Configuration File

# Whether to render baubles on players
render_baubles: true

# Whether to enable right-click equipping of baubles
enable_right_click_equip: true

# Whether to save player bauble data on logout
save_data_on_logout: true

# Debug settings
debug:
  # Enable debug logging
  enabled: false
  # Log bauble equip/unequip events
  log_equip_events: false