name: SevenToDie
version: 1.0.0
main: com.seventodie.SevenToDie
api-version: '1.19'
description: Adds 7 bauble slots to player inventory (amulet, belt, head, body, charm, 2 rings)
authors: [AzazelX]
commands:
  baubles:
    description: Access your baubles inventory
    usage: /baubles [help|list]
    permission: seventodie.baubles
    aliases: [bauble, b]
permissions:
  seventodie.baubles:
    description: Allows access to baubles inventory
    default: true